# This is a basic action that sanitizes the
# code before it gets mastered

name: Code Sanitation

# Specifies when the action is going to be triggered
on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

  # Manual trigger for testin purposes
  workflow_dispatch:
  

jobs:
  sanitize_code:
    name: Tidy Up
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2.3.4

      - name: Install NPM packages
        run: npm install -D

      - name: Run SASS
        run: npm run sass
        
      - name: Run Babel
        run: npm run babel

      - name: Commits dist/ to master
        run: |
          git config --global user.email "${{ secrets.USER_NAME }}" 
          git config --global user.name "${{ secrets.USER_EMAIL }}"
          mv .gitignore gitignore
          git add dist
          mv gitignore .gitignore
          git commit -m "[=] dist/ updated;"
          git push origin master
