# This is a basic action that sanitizes the
# code before it gets mastered

name: Code Sanitation

# Specifies when the action is going to be triggered
on:
  # Trigger the workflow on push to the master branch
  pull_request:
    types: [open, reopened]
    branches: [master]

  pull_request_review:
    types: [submitted]
    branches: [master]

  # Manual trigger for testin purposes
  workflow_dispatch:
  

jobs:
  sanitize_code:
    name: Tidy Up
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2.3.4

      - name: Install NPM packages
        run: npm install -D

      - name: Compile and sanitize code
        run: |
          npm run compile

          # GitHub like identation with spaces more
          bash .github/workflows/code-sanitation/tabs-to-spaces.sh '*.scss *.js' 2

      - name: Commits dist/ to current branch
        run: |
          git config --global user.email "${{ secrets.USER_NAME }}" 
          git config --global user.name "${{ secrets.USER_EMAIL }}"

          git status
          git add all
          git commit -m "[=] tabs replaced with spaces;"
          git push origin ${GITHUB_REF##*/}
