# This is a basic action that sanitizes the
# code before it gets mastered
#
# TODO:
# - use the GitHub token for authentication;
# - checkout the current branch before you commit the sanitation;
# - chech in bash if all is up-to-date before the commit;

name: Code Sanitation

# Specifies when the action is going to be triggered
on:
  workflow_dispatch:
  

jobs:
  sanitize_code:
    name: Tidy Up
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2.3.4

      - name: Install NPM packages
        run: npm install -D

      - name: Compile and sanitize code
        run: |
          npm run compile

          # GitHub like identation with spaces more
          bash .github/workflows/code-sanitation/tabs-to-spaces.sh '*.scss *.js' 2

      - name: Commits changes to current branch
        run: |
          git config --global user.email "sanitation-bot@users.noreply.github.com" 
          git config --global user.name "Sanitation Bot"

          git status
          git add -A
          git commit -m "[=] sanitation complete;"
          git push
